### ISSUE TITLE
send multinuber "134" with smarthings->broadlink

### ISSUE THREAD

**Issue by mercedescls** [beckyricha/Broadlink-RM-SmartThings-Alexa#15]
can i send to the tv channel 128 (multi numbers) /combo like Device name "HBO" which is on schedule/number "134" ?  i use RM Bridge.  (by the way Google home->smarthings->Rm Bridge->broadlink It works well )

**Comment by beckyricha** [comment]
Yes.  You can do it now with multi keys, but I am also working on a smart app I hope to release in the next couple of days to let you set up keys 0-9 using any device (broadlink, harmony, other...) and easily input channel names and numbers the app would control.  I wanted to link it to schedules direct or some other lineup grabber tool, but am having enough trouble as it is. I want to finish tomorrow but am having issues wiht a SmartApp command whose syntax seems to have changed.  If i get a mostly useful version, but without the fancy smartApp stuff, I'll release it anyway for people to play with.

Based on some of the other things I am seeing on tho forum, I may also try to write a smartApp to set up Broadlink devices, without the fun2code setup step. (you would still need the bridge but maybe could set it all up from your ST app in a single step - that's one for later though).

**Comment by mercedescls** [comment]
it's amazing !!!!!!!!! yeeeeeeeeeeee

**Comment by mercedescls** [comment]
all it's work greate !

**Comment by mercedescls** [comment]
but if i whant to change channels like: HBO(135) after 5s CNN(165) , BBC (32)  how can i do ?

**Comment by beckyricha** [comment]
You should just be able to say turn on the next channel ID if they're all programmed in as devices (the process i hope to make easier with the other app I'm working on). Since you never say turn off this won't keep visual good switch states in smart things but would be good in the echo or Google home.  You can turn them on even if they're already on so the functionality is fine.
Are you having any difficulty with making that work?
On Jan 13, 2017 5:59 AM, mercedescls <notifications@github.com> wrote:but if i whant to change channels like: HBO(135) after 5s CNN(165) , BBC (32)  how can i do ?

**Comment by mercedescls** [comment]
i don't understand because each chanel is whith multikey (135) isn't whit single key (9). can you explain me how can i shoud do ?

**Comment by beckyricha** [comment]
There are two ways. One is to make a new device for each channel, calling them multikeys device type. Then you record the keys you need on the rm bridge like you did before but call them "[your channel name]  on1" - record the 1 key;  "[your channel name]  on2" - record the 3 key, etc. 
Method 2 will only work if you have a smart things hub, but later today i hope to post some code you can try. This will let you record keys 0 - 9 on the rm bridge (or any device that works with smart things) and then use smart apps to enter and manage the channels as virtual devices.
On Jan 13, 2017 7:43 AM, mercedescls <notifications@github.com> wrote:i don't understand because each chanel is whith multikey (135) isn't whit single key (9). can you explain me how can i shoud do ?

**Comment by mercedescls** [comment]
i have smartthings and G H...until now it's amazing but i whant do change 8 channels (with multikey each) with one command like "preview channels" every 5,6 seconds(145  5s  183 5s 93 5s 8 5s... )  pls help me with this

**Comment by beckyricha** [comment]
I can't take that one on right now, but can point you in the right direction and offer some help as you go, if you'd like to try it yourself. I'm also about to post some code that works using a similar concept that you could adapt for this purpose without too much trouble if you've done any programming before.
I think what you would need is a custom device type for your "preview channels" device.  Feel free to use the "dummySwitch" that will be part of my TV channel control project when i post it.  It doesn't need to do anything but be a placeholder.
Then you need a smart App that listens for this device.  My "TV channels handler" app will have this feature so you can see how it works.   My app will listen for a device and then use the channel's number to send key strokes to devices representing 0-9.  Yours would need to change this.  The easiest way would be for you to hard code a series of channels to switch and move on. However, you may not be able to stop it until after it finishes.  Getting fancier than that I'm afraid you would need to research on your own. There's a lot of smart things code out there to help get started and a nice reference suite that explains what all the command and their arguments mean.
If you do try and run into hiccups I'd be happy to answer questions to the extent i can.
Becky
On Jan 13, 2017 10:41 AM, mercedescls <notifications@github.com> wrote:i have smartthings and G H...until now it's amazing but i whant do change 8 channels (with multikey each) with one command like "preview channels" every 5,6 seconds(145  5s  183 5s 93 5s 8 5s... )  pls help me with this

**Comment by beckyricha** [comment]
I have now posted the channel adder I mentioned, in a beta form for testing.  Check it out at https://beckyricha.github.io/SmartThings-TV-Channels.html

**Comment by mercedescls** [comment]
Now i have a GH->smartthings hub->android->rm pro. If i buy a rm mini3 how is work with both?

**Comment by beckyricha** [comment]
I haven't used the mini but i think it works the same way. If you want to find out about whether it works with the rm bridge please contact the rm bridge developer. If it does work, the setup should be exactly the same.
On Jan 15, 2017 7:19 PM, mercedescls <notifications@github.com> wrote:Now i have a GH->smartthings hub->android->rm pro. If i buy a rm mini3 how is work with both?

**Comment by mercedescls** [comment]
def on() {
	sendEvent(name: "switch", value: "on")
    delayBetween( [ delayBetween([put('on'),put('on2'),put('on3'),put('on4')],1000)
                    ,delayBetween([put0('on')],2000)
                    ,delayBetween([put2('on'),put2('on2'),put2('on3'),put2('on4')],1000)
                    ,delayBetween([put0('on')],2000)
                    ,delayBetween([put3('on'),put3('on2'),put3('on3'),put3('on4')],1000)
                    ,delayBetween([put0('on')],2000)
                    ,delayBetween([put4('on'),put4('on2'),put4('on3'),put4('on4')],1000)
                    ,delayBetween([put0('on')],2000)
                    ,delayBetween([put5('on'),put5('on2'),put5('on3'),put5('on4')],1000)
                    ,delayBetween([put0('on')],2000)
                    ,delayBetween([put6('on'),put6('on2'),put6('on3'),put6('on4')],1000)
                    ,delayBetween([put0('on')],2000)
                    ,delayBetween([put7('on'),put7('on2'),put7('on3'),put7('on4')],1000)
                    ,delayBetween([put0('on')],2000)

    ],7000)
 
}

 
private put(toggle) {
	def url1="192.168.0.235:7474"
    def userpassascii= "username:password"
    def userpass = "Basic " + userpassascii.encodeAsBase64().toString()
    def toReplace = device.displayName
	def replaced = toReplace.replaceAll(' ', '%20')
 	def hubaction = new physicalgraph.device.HubAction(
				method: "GET",
               path: "/code/protv%20$toggle",
               headers: [HOST: "${url1}", AUTHORIZATION: "${userpass}"])
   			return hubaction
   }
private put2(toggle) {
	def url1="192.168.0.235:7474"
    def userpassascii= "username:password"
    def userpass = "Basic " + userpassascii.encodeAsBase64().toString()
    def toReplace = device.displayName
	def replaced = toReplace.replaceAll(' ', '%20')
 	def hubaction = new physicalgraph.device.HubAction(
				method: "GET",
               path: "/code/antena%20one%20$toggle",
               headers: [HOST: "${url1}", AUTHORIZATION: "${userpass}"])
   			return hubaction
   }   
private put3(toggle) {
	def url1="192.168.0.235:7474"
    def userpassascii= "username:password"
    def userpass = "Basic " + userpassascii.encodeAsBase64().toString()
    def toReplace = device.displayName
	def replaced = toReplace.replaceAll(' ', '%20')
 	def hubaction = new physicalgraph.device.HubAction(
				method: "GET",
               path: "/code/kanal%20d%20$toggle",
               headers: [HOST: "${url1}", AUTHORIZATION: "${userpass}"])
   			return hubaction
   }      
private put4(toggle) {
	def url1="192.168.0.235:7474"
    def userpassascii= "username:password"
    def userpass = "Basic " + userpassascii.encodeAsBase64().toString()
    def toReplace = device.displayName
	def replaced = toReplace.replaceAll(' ', '%20')
 	def hubaction = new physicalgraph.device.HubAction(
				method: "GET",
               path: "/code/hbo%20one%20$toggle",
               headers: [HOST: "${url1}", AUTHORIZATION: "${userpass}"])
   			return hubaction
   }      
private put5(toggle) {
	def url1="192.168.0.235:7474"
    def userpassascii= "username:password"
    def userpass = "Basic " + userpassascii.encodeAsBase64().toString()
    def toReplace = device.displayName
	def replaced = toReplace.replaceAll(' ', '%20')
 	def hubaction = new physicalgraph.device.HubAction(
				method: "GET",
               path: "/code/hbo%20two%20$toggle",
               headers: [HOST: "${url1}", AUTHORIZATION: "${userpass}"])
   			return hubaction
   }   
private put6(toggle) {
	def url1="192.168.0.235:7474"
    def userpassascii= "username:password"
    def userpass = "Basic " + userpassascii.encodeAsBase64().toString()
    def toReplace = device.displayName
	def replaced = toReplace.replaceAll(' ', '%20')
 	def hubaction = new physicalgraph.device.HubAction(
				method: "GET",
               path: "/code/hbo%20three%20$toggle",
               headers: [HOST: "${url1}", AUTHORIZATION: "${userpass}"])
   			return hubaction
   }      
 private put7(toggle) {
	def url1="192.168.0.235:7474"
    def userpassascii= "username:password"
    def userpass = "Basic " + userpassascii.encodeAsBase64().toString()
    def toReplace = device.displayName
	def replaced = toReplace.replaceAll(' ', '%20')
 	def hubaction = new physicalgraph.device.HubAction(
				method: "GET",
               path: "/code/digi%20film%20$toggle",
               headers: [HOST: "${url1}", AUTHORIZATION: "${userpass}"])
   			return hubaction
   }
 private put0(toggle) {
	def url1="192.168.0.235:7474"
    def userpassascii= "username:password"
    def userpass = "Basic " + userpassascii.encodeAsBase64().toString()
    def toReplace = device.displayName
	def replaced = toReplace.replaceAll(' ', '%20')
 	def hubaction = new physicalgraph.device.HubAction(
				method: "GET",
               path: "/code/info%20on",
               headers: [HOST: "${url1}", AUTHORIZATION: "${userpass}"])
   			return hubaction
   }
   
 
def parse(description) {

}

**Comment by mercedescls** [comment]
like this i change 7 channels
