### ISSUE TITLE
Rm Tasker cloud version 

### ISSUE THREAD

**Issue by accom06** [beckyricha/Broadlink-RM-SmartThings-Alexa#4]
Hi Becky, 

Really appreciate your work here. 

I have a bunch of SP mini plugs that unfortunately does not work with Rmbridge. I wonder if you could send me the working file for your Rm Tasker Cloud version? 

Thanks!

**Comment by beckyricha** [comment]
Sure. I have not used it in a while but will give it a look tomorrow and post it.  
Becky
On Oct 20, 2016 1:42 PM, Aaron <notifications@github.com> wrote:Hi Becky, 

Really appreciate your work here. 

I have a bunch of SP mini plugs that unfortunately does not work with Rmbridge. I wonder if you could send me the working file for your Rm Tasker Cloud version? 

Thanks!

**Comment by accom06** [comment]
Hi Becky, 

I managed to rewrite your LAN coding and got it working! 

Thanks!

**Comment by beckyricha** [comment]
Sorry I missed this.  In case anyone wants it, I am adding the tasker cloud version to the repo.
