### ISSUE TITLE
Google home

### ISSUE THREAD

**Issue by mercedescls** [beckyricha/Broadlink-RM-SmartThings-Alexa#6]
How can i link google home to broadlink? can you help me?

**Comment by beckyricha** [comment]
I don't have a Google home so i don't know what it can do. If it will connect to smart things like Alexa does, you would follow all of the steps here to create smart things devices, which can then be used by any other services that can access smart things.
On Nov 21, 2016 8:10 AM, mercedescls <notifications@github.com> wrote:How can i link google home to broadlink? can you help me?

**Comment by mercedescls** [comment]
Do you have alexa amazon?

**Comment by itsamti** [comment]
This code works with Smartthings and has nothing to do with Amazon Echo (Alexa) or Google Home. 

Amazon Echo and Google Home connects to smartthings. Having said that, if you can ON/OFF RM bridge switches using smartthings app; it will work using echo or google home.

**Comment by mercedescls** [comment]
Tks all

**Comment by mercedescls** [comment]
do i need to put only Broadlink RM Bridge Switch LAN or i need to put Broadlink RM Bridge Switch LAN and Broadlink LAN SmartApp? i don't understend for what is Broadlink LAN SmartApp

**Comment by beckyricha** [comment]
Sorry, I guess I didn't explain that as this project evolved. I forgot it was there and haven't used it in a long time but you don't need it to get started. It is a tool to bring several existing devices under this device type or remove them all at once.  It may have utility for some people but I'd recommend just starting without it, following the instructions, to get going. I did not make sure it still works right after bringing in some other people's ideas on the device type.
I have been working on another project but will get back and do some maintenance and clean up on this soon.  Thanks.
Becky
On Nov 23, 2016 5:06 AM, mercedescls <notifications@github.com> wrote:do i need to put only Broadlink RM Bridge Switch LAN or i need to put Broadlink RM Bridge Switch LAN and Broadlink LAN SmartApp? i don't understend for what is Broadlink LAN SmartApp

**Comment by mercedescls** [comment]
With alexa you can change chanels on tv like:alexa change on mtv ?

**Comment by beckyricha** [comment]
Not directly out of the box. I can do this with my TV but had to do some time consuming programming to make it happen.  I also use a Windows pc for my TV so the system is probably different.  Using the setup I describe here you might be able to program a series of commands into your broadlink, and name that mtv, but you would need to be willing to noodle with the code a bit to run a sequence of commands, depending on what sort of setup you have. 
So yes, technically it can be done. I run my TV this way (and it's awesome). But this would require you to have some technical skills and be willing to experiment and write some code. An easier way might be to invest in a harmony hub. I don't have one, but my understanding is you could more easily setup up channels for Alexa control using that. You'd have to research it to see if I'm right about that or maybe someone who has one could weigh in.
On Nov 27, 2016 4:02 PM, mercedescls <notifications@github.com> wrote:With alexa you can change chanels on tv like:alexa change on mtv ?

**Comment by af950833** [comment]
With beckyricha's smartthings cloud, we can link the Google Home with Broadlink.
It works well with Alexa and Google home.
But I recommend a easy way.
You have to set up a bridge with RM Takser Plugin(In the app, you have to enable HTTP Bridge) or RM Bridge.
And then, go to IFTTT..
As a trigger, select the Google Assistant. You can make your own trigger words with it.
As a action, selet the Maker. The maker can send a http POST / Get to your RM Pro.
You need also set up your router's port forward.
Good luck to you.

**Comment by beckyricha** [comment]
Yes, I've heard that is an advantage for Google that hopefully Amazon can match. With Alexa, you kept having to say "trigger,"  which got  old quickly. I think google home lets your activate it with a custom phrase. Is that correct?
On Dec 4, 2016 3:14 AM, af950833 <notifications@github.com> wrote:With beckyricha's smartthings cloud, we can link the Google Home with Broadlink.
It works well with Alexa and Google home.
But I recommend a easy way.
You have to set up a bridge with RM Takser Plugin(In the app, you have to enable HTTP Bridge) or RM Bridge.
And then, go to IFTTT..
As a trigger, select the Google Assistant. You can make your own trigger words with it.
As a action, selet the Maker. The maker can send a http POST / Get to your RM Pro.
You need also set up your router's port forward.
Good luck to you.

**Comment by af950833** [comment]
Yes, right.
IFTTT for the Google assistant lets us to use 3 phrases at one recipe.
Also we can make a custom phrase with number & text ingredient like a variable.

**Comment by mercedescls** [comment]
alexa->broadlink can send to the tv channel 128 (multi numbers) or can send broadlink tv ->more->combo button ???
