### ISSUE TITLE
using rm bridge cloud

### ISSUE THREAD

**Issue by dericion** [beckyricha/Broadlink-RM-SmartThings-Alexa#9]
hi im staying in singapore. after trying rm tasker for a while it is extremely unstable.

im now trying out yr rm bridge cloud but doesnt seems to work. trying to discover devices on alexa didnt bring out any of the devices that i saved. trying them out on smartthings also doesnt seems to work.

**Comment by dericion** [comment]
hi, self resolved. its the on and off that stops the operation from working. but may i know if i can create a scene whereby i ask alexa to turn on e.g home theatre and it will turn on the tv, turn on the amplifier and also turn on my ceiling fan?

**Comment by beckyricha** [comment]
As long as they are all 'on' this is the easiest scenario. In the Alexa app you can create a group of devices with a new name, and they all turn on and off together. You do this after you import the devices from smart things. It is a little harder with some devices on while others turn off, but lately Alexa has started recognizing smart things scenes. You would have to make more complicated scenes there and connect those to Alexa. Hope this helps.
Becky
On Dec 16, 2016 10:27 PM, dericion <notifications@github.com> wrote:hi, self resolved. its the on and off that stops the operation from working. but may i know if i can create a scene whereby i ask alexa to turn on e.g home theatre and it will turn on the tv, turn on the amplifier and also turn on my ceiling fan?
